name: Studysense
description: "A new flutter project"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  sqflite_android: ^2.3.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.3
  path: ^1.8.3
  http: ^1.6.0
  supabase_flutter: ^2.15.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  dio: ^5.3.1
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.1
  flutter_lints: ^6.0.0
    
flutter:
  uses-material-design: true
  # assets:
  #   -
  # fonts:
  #   - family: 
